pub mod add_sources;
pub mod bench;
pub mod bodies;
pub mod checks;
pub mod clock;
pub mod degraded;
pub mod exchanges;
pub mod cut;
pub mod icons;
pub mod layout;
pub mod migrate;
pub mod narration;
pub mod new_project;
pub mod project;
pub mod prepare;
pub mod publish;
pub mod probes;
pub mod rescan;
pub mod requests;
pub mod roles;
pub mod run;
pub mod save_as;
pub mod separate;
pub mod services;
pub mod settings;
pub mod shell;
pub mod snapshot;
pub mod sources;
pub mod startup;
pub mod subprocess;
pub mod textfmt;
pub mod transcribe;
pub mod tools;
pub mod wave;
pub mod ui;

/// The four pages, in the order the user works through them (spec/00-principles.md §1).
pub const PAGES: [&str; 4] = ["Prepare", "Cut", "Narrate", "Produce"];
